// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnf66TyXgP0YWcu9stIIKY-z-phn5y8P4',
    appId: '1:341013989759:web:d1d71c362d72508c73b24a',
    messagingSenderId: '341013989759',
    projectId: 'my-project-with-almotaz',
    authDomain: 'my-project-with-almotaz.firebaseapp.com',
    storageBucket: 'my-project-with-almotaz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSm0jOW39ZNy8PtZLLQwVuOaabGELogLs',
    appId: '1:341013989759:android:d1072d18d727ba3073b24a',
    messagingSenderId: '341013989759',
    projectId: 'my-project-with-almotaz',
    storageBucket: 'my-project-with-almotaz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRPL-OZ64akc4RhWrwMAinz3uP5pf8KPc',
    appId: '1:341013989759:ios:71e4b322dbe59e0f73b24a',
    messagingSenderId: '341013989759',
    projectId: 'my-project-with-almotaz',
    storageBucket: 'my-project-with-almotaz.appspot.com',
    iosClientId: '341013989759-onmh12vmaqq0934q7n21prn0nlq2gt8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mohammadShboul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRPL-OZ64akc4RhWrwMAinz3uP5pf8KPc',
    appId: '1:341013989759:ios:71e4b322dbe59e0f73b24a',
    messagingSenderId: '341013989759',
    projectId: 'my-project-with-almotaz',
    storageBucket: 'my-project-with-almotaz.appspot.com',
    iosClientId: '341013989759-onmh12vmaqq0934q7n21prn0nlq2gt8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mohammadShboul',
  );
}
